
export const sampleData = [
  {
    title: "Maaş",
    amount: 15000,
    type: "income",
    category: "İş",
    date: "2026-05-01",
  },
  {
    title: "Burs",
    amount: 2500,
    type: "income",
    category: "Eğitim",
    date: "2026-05-02",
  },
  {
    title: "Freelance Web Tasarım",
    amount: 4200,
    type: "income",
    category: "Freelance",
    date: "2026-05-03",
  },
  {
    title: "Harçlık",
    amount: 1000,
    type: "income",
    category: "Aile",
    date: "2026-05-04",
  },
  {
    title: "Staj Ödemesi",
    amount: 3500,
    type: "income",
    category: "Staj",
    date: "2026-05-05",
  },
  {
    title: "Market",
    amount: 850,
    type: "expense",
    category: "Gıda",
    date: "2026-05-06",
  },
  {
    title: "Kira",
    amount: 5500,
    type: "expense",
    category: "Ev",
    date: "2026-05-07",
  },
  {
    title: "Elektrik Faturası",
    amount: 620,
    type: "expense",
    category: "Fatura",
    date: "2026-05-08",
  },
  {
    title: "İnternet Faturası",
    amount: 480,
    type: "expense",
    category: "Fatura",
    date: "2026-05-09",
  },
  {
    title: "Su Faturası",
    amount: 230,
    type: "expense",
    category: "Fatura",
    date: "2026-05-10",
  },
  {
    title: "Doğalgaz",
    amount: 700,
    type: "expense",
    category: "Fatura",
    date: "2026-05-11",
  },
  {
    title: "Otobüs Kartı",
    amount: 300,
    type: "expense",
    category: "Ulaşım",
    date: "2026-05-12",
  },
  {
    title: "Taksi",
    amount: 220,
    type: "expense",
    category: "Ulaşım",
    date: "2026-05-13",
  },
  {
    title: "Kahve",
    amount: 150,
    type: "expense",
    category: "Sosyal",
    date: "2026-05-14",
  },
  {
    title: "Yemek Siparişi",
    amount: 340,
    type: "expense",
    category: "Yemek",
    date: "2026-05-15",
  },
  {
    title: "Kitap",
    amount: 420,
    type: "expense",
    category: "Eğitim",
    date: "2026-05-16",
  },
  {
    title: "Udemy Kursu",
    amount: 280,
    type: "expense",
    category: "Eğitim",
    date: "2026-05-17",
  },
  {
    title: "GitHub Pro",
    amount: 150,
    type: "expense",
    category: "Yazılım",
    date: "2026-05-18",
  },
  {
    title: "Domain Ücreti",
    amount: 600,
    type: "expense",
    category: "Web",
    date: "2026-05-19",
  },
  {
    title: "Hosting",
    amount: 900,
    type: "expense",
    category: "Web",
    date: "2026-05-20",
  },
  {
    title: "Telefon Faturası",
    amount: 390,
    type: "expense",
    category: "Fatura",
    date: "2026-05-21",
  },
  {
    title: "Spor Salonu",
    amount: 750,
    type: "expense",
    category: "Sağlık",
    date: "2026-05-22",
  },
  {
    title: "İlaç",
    amount: 180,
    type: "expense",
    category: "Sağlık",
    date: "2026-05-23",
  },
  {
    title: "Kıyafet",
    amount: 1200,
    type: "expense",
    category: "Giyim",
    date: "2026-05-24",
  },
  {
    title: "Ayakkabı",
    amount: 1800,
    type: "expense",
    category: "Giyim",
    date: "2026-05-25",
  },
  {
    title: "Mouse",
    amount: 450,
    type: "expense",
    category: "Teknoloji",
    date: "2026-05-26",
  },
  {
    title: "Klavye",
    amount: 900,
    type: "expense",
    category: "Teknoloji",
    date: "2026-05-27",
  },
  {
    title: "Kulaklık",
    amount: 1100,
    type: "expense",
    category: "Teknoloji",
    date: "2026-05-28",
  },
  {
    title: "Oyun Satın Alma",
    amount: 350,
    type: "expense",
    category: "Eğlence",
    date: "2026-05-29",
  },
  {
    title: "Sinema",
    amount: 250,
    type: "expense",
    category: "Eğlence",
    date: "2026-05-30",
  },
  {
    title: "Netflix",
    amount: 230,
    type: "expense",
    category: "Abonelik",
    date: "2026-05-31",
  },
  {
    title: "Spotify",
    amount: 100,
    type: "expense",
    category: "Abonelik",
    date: "2026-06-01",
  },
  {
    title: "YouTube Premium",
    amount: 80,
    type: "expense",
    category: "Abonelik",
    date: "2026-06-02",
  },
  {
    title: "Adobe Planı",
    amount: 800,
    type: "expense",
    category: "Yazılım",
    date: "2026-06-03",
  },
  {
    title: "Figma Planı",
    amount: 350,
    type: "expense",
    category: "Yazılım",
    date: "2026-06-04",
  },
  {
    title: "Unreal Asset",
    amount: 500,
    type: "expense",
    category: "Oyun",
    date: "2026-06-05",
  },
  {
    title: "Firebase Kullanımı",
    amount: 120,
    type: "expense",
    category: "Yazılım",
    date: "2026-06-06",
  },
  {
    title: "MongoDB Cloud",
    amount: 170,
    type: "expense",
    category: "Yazılım",
    date: "2026-06-07",
  },
  {
    title: "Postman Planı",
    amount: 90,
    type: "expense",
    category: "Yazılım",
    date: "2026-06-08",
  },
  {
    title: "Kodlama Kitabı",
    amount: 380,
    type: "expense",
    category: "Eğitim",
    date: "2026-06-09",
  },
  {
    title: "Kahvaltı",
    amount: 160,
    type: "expense",
    category: "Yemek",
    date: "2026-06-10",
  },
  {
    title: "Öğle Yemeği",
    amount: 220,
    type: "expense",
    category: "Yemek",
    date: "2026-06-11",
  },
  {
    title: "Akşam Yemeği",
    amount: 280,
    type: "expense",
    category: "Yemek",
    date: "2026-06-12",
  },
  {
    title: "Temizlik Malzemesi",
    amount: 450,
    type: "expense",
    category: "Ev",
    date: "2026-06-13",
  },
  {
    title: "Ev Eşyası",
    amount: 700,
    type: "expense",
    category: "Ev",
    date: "2026-06-14",
  },
  {
    title: "Kuaför",
    amount: 300,
    type: "expense",
    category: "Kişisel Bakım",
    date: "2026-06-15",
  },
  {
    title: "Parfüm",
    amount: 850,
    type: "expense",
    category: "Kişisel Bakım",
    date: "2026-06-16",
  },
  {
    title: "Benzin",
    amount: 1100,
    type: "expense",
    category: "Araç",
    date: "2026-06-17",
  },
  {
    title: "Araç Bakımı",
    amount: 2500,
    type: "expense",
    category: "Araç",
    date: "2026-06-18",
  },
  {
    title: "Hisse Alımı",
    amount: 3000,
    type: "expense",
    category: "Yatırım",
    date: "2026-06-19",
  },
  {
    title: "Fon Alımı",
    amount: 2000,
    type: "expense",
    category: "Yatırım",
    date: "2026-06-20",
  },
  {
    title: "Kripto Alımı",
    amount: 1000,
    type: "expense",
    category: "Yatırım",
    date: "2026-06-21",
  },
  {
    title: "React Projesi",
    amount: 4500,
    type: "income",
    category: "Freelance",
    date: "2026-06-22",
  },
  {
    title: "Firebase Projesi",
    amount: 3000,
    type: "income",
    category: "Freelance",
    date: "2026-06-23",
  },
  {
    title: "Logo Tasarım",
    amount: 1600,
    type: "income",
    category: "Tasarım",
    date: "2026-06-24",
  },
  {
    title: "Portfolyo Site Geliri",
    amount: 2500,
    type: "income",
    category: "Web",
    date: "2026-06-25",
  },
  {
    title: "Danışmanlık",
    amount: 2200,
    type: "income",
    category: "Danışmanlık",
    date: "2026-06-26",
  },
  {
    title: "YouTube Geliri",
    amount: 1100,
    type: "income",
    category: "İçerik",
    date: "2026-06-27",
  },
  {
    title: "Blog Reklam Geliri",
    amount: 900,
    type: "income",
    category: "Web",
    date: "2026-06-28",
  },
  {
    title: "Mini Proje",
    amount: 2800,
    type: "income",
    category: "Proje",
    date: "2026-06-29",
  },
];

